### ISSUE TITLE
Steps for rebuilding docker image after code changes

### ISSUE THREAD

**Issue by darwapls** [manooog/jsproxy-docker#1]
Can you please guide on how to make changes to the code (like customizing homepage), after building a local development stage?

What are the steps for rebuilding the image after making code changes?

Thanks!

**Comment by manooog** [comment]
OH,thanks for your star.Maybe you can take the steps below:

1、start a container
```
docker run -d  -p 8080:8080 --name jsproxy  rxh1212/jsproxy
```
2、into the container
```
docker exec -it jsproxy bash
```
3、make some changes & test

For example,if you want change the homepage,you can modify this file:

`/home/jsproxy/server/www/assets/index_v3.html`

Then,reload the openresty server with:

```
/home/jsproxy/server/run.sh reload
```

4、save container to a new image
```
docker commit jsproxy <image-name>:<tag>
```

**Comment by darwapls** [comment]
Thank you so much. I will give that a try later today :)
