### ISSUE TITLE
关于https转发

### ISSUE THREAD

**Issue by jotony** [manooog/jsproxy-docker#2]
可以详细说下nginx的配置吗，  我转发端口到127.0.0.1:8080  访问的时候自动跳转到https://domain.com:8443

**Comment by zh-cmn** [comment]
proxy_set_header Host 127.0.0.1

**Comment by manooog** [comment]
@jotony 我写了一个配置示例，你看下是否对你有帮助。

https://github.com/manooog/jsproxy-docker/blob/master/example/nginx.md#nginx-config
