### ISSUE TITLE
现在是否还能使用，按照readme执行docker pull和docker run之后，站点能打开，但是无法访问任何网站

### ISSUE THREAD

**Issue by seepine** [manooog/jsproxy-docker#3]
![image](https://user-images.githubusercontent.com/93666053/186296365-676450e9-f74e-4a76-873a-86b4e93d33ad.png)

**Comment by manooog** [comment]
这是个代理工具，能不能打开 google.com，是看运行这个工具的机器网络是否支持访问 google.com。

这个工具自己不带 fq 功能的哈。
